### ISSUE TITLE
Updates to 'Contact' section

### ISSUE THREAD

**Issue by evert** [badgateway/badgateway.net#6]
Do you have an easy way to implement this contact form? It's a bit of a pain because we probably need captcha as well to avoid overwhelming spam... 

If no, maybe we just need to show an email address on the Contact section with some flavor text...

**Comment by ikbensiep** [comment]
Maybe a service like [getform](https://getform.io/installations) is worth looking into.
Seems easy enough to implement, they implement Akismet spam filtering, and also have documentation on how to implement ReCaptcha (2 and 3).

Free plan is 50 submissions/mo so, no harm in trying it out?

**Comment by evert** [comment]
If either is easy, and it can just forward to info@badgateway.net it sounds good to me!

In that case I would want to suggest:

* Drop the select box and budget input
* Include an email address anyway for people that prefer to just use their mail client.
* Maybe it's worth also just adding this link? https://calendly.com/evert-bg/30min

**Comment by ikbensiep** [comment]
Cool, I can work with this ^_^
